// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGltT5CgeT22FXbMNn3qE9q_ZRbf4GuTk',
    appId: '1:374274231189:web:249af6e8d33ec48945449c',
    messagingSenderId: '374274231189',
    projectId: 'kasku-f7c18',
    authDomain: 'kasku-f7c18.firebaseapp.com',
    storageBucket: 'kasku-f7c18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATJ9wE7dT_ewSRUWGerfnvrUqmrygA4Lw',
    appId: '1:374274231189:android:7dab087f6192839445449c',
    messagingSenderId: '374274231189',
    projectId: 'kasku-f7c18',
    storageBucket: 'kasku-f7c18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5FzD37sYx1d4549UBpxRDKrTvHEMXUhw',
    appId: '1:374274231189:ios:371a3cf1b8923c7045449c',
    messagingSenderId: '374274231189',
    projectId: 'kasku-f7c18',
    storageBucket: 'kasku-f7c18.firebasestorage.app',
    iosBundleId: 'com.example.kaskuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5FzD37sYx1d4549UBpxRDKrTvHEMXUhw',
    appId: '1:374274231189:ios:371a3cf1b8923c7045449c',
    messagingSenderId: '374274231189',
    projectId: 'kasku-f7c18',
    storageBucket: 'kasku-f7c18.firebasestorage.app',
    iosBundleId: 'com.example.kaskuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGltT5CgeT22FXbMNn3qE9q_ZRbf4GuTk',
    appId: '1:374274231189:web:dc783e14056896f345449c',
    messagingSenderId: '374274231189',
    projectId: 'kasku-f7c18',
    authDomain: 'kasku-f7c18.firebaseapp.com',
    storageBucket: 'kasku-f7c18.firebasestorage.app',
  );
}
